import { NextRequest, NextResponse } from 'next/server';
import { listMonitors, setMonitor } from '@/lib/serverStore';
import { dispatchMonitorNotification } from '@/lib/notifier';
import { severeAlertDelta } from '@/lib/monitorAlertState';
import { riskForPlan, rainTiming } from '@/lib/weather';
export const dynamic = 'force-dynamic'; export const maxDuration = 60;
async function getJson(url:string,headers?:Record<string,string>){const r=await fetch(url,{headers,cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return r.json();}
async function weatherAt(lat:number,lon:number){const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',String(lat));u.searchParams.set('longitude',String(lon));u.searchParams.set('timezone','auto');u.searchParams.set('forecast_days','16');u.searchParams.set('temperature_unit','fahrenheit');u.searchParams.set('wind_speed_unit','mph');u.searchParams.set('precipitation_unit','inch');u.searchParams.set('hourly','precipitation_probability,precipitation,temperature_2m,wind_speed_10m,weather_code');u.searchParams.set('daily','temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max,snowfall_sum');return getJson(u.toString());}
async function alertsAt(lat:number,lon:number){return getJson(`https://api.weather.gov/alerts/active?point=${lat.toFixed(4)},${lon.toFixed(4)}`,{Accept:'application/geo+json','User-Agent':'SkyWatch Weather Monitor'}).catch(()=>({features:[]}));}
async function aqiAt(lat:number,lon:number){return getJson(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&current=us_aqi&timezone=auto`).catch(()=>({current:{}}));}
async function lightningAt(lat:number,lon:number){if(!process.env.LIGHTNING_FEED_URL)return null;try{const u=new URL(process.env.LIGHTNING_FEED_URL);u.searchParams.set('lat',String(lat));u.searchParams.set('lon',String(lon));return await getJson(u.toString());}catch{return null}}
function lightningDistance(data:any){if(typeof data?.nearestMiles==='number')return data.nearestMiles;const vals=(data?.strikes||[]).map((s:any)=>Number(s.distanceMiles??s.distance_miles)).filter(Number.isFinite);return vals.length?Math.min(...vals):null;}
function meaningfulPlanChange(prev:any,next:any){if(!prev)return false;if(prev.level!==next.level)return true;return Math.abs((prev.rain||0)-(next.rain||0))>=15||Math.abs((prev.wind||0)-(next.wind||0))>=5||Math.abs((prev.high||0)-(next.high||0))>=5||Math.abs((prev.low||0)-(next.low||0))>=5;}
export async function GET(req:NextRequest){
 const secret=process.env.CRON_SECRET;if(secret&&req.headers.get('authorization')!==`Bearer ${secret}`)return NextResponse.json({error:'Unauthorized'},{status:401});
 const monitors=await listMonitors();const summary:any[]=[];
 for(const {id,data:m} of monitors.slice(0,100)){try{const loc=m.location||m.plans?.[0]?.location;if(!loc)continue;const [w,a,aq,lt]=await Promise.all([weatherAt(loc.latitude,loc.longitude),alertsAt(loc.latitude,loc.longitude),m.preferences?.aqi?aqiAt(loc.latitude,loc.longitude):Promise.resolve(null),m.preferences?.lightning?lightningAt(loc.latitude,loc.longitude):Promise.resolve(null)]);const state={...(m.state||{})};const sent:string[]=[];
   if(m.preferences?.officialSevere!==false){const delta=severeAlertDelta(a.features||[],state);for(const alert of delta.unseen){const p=alert.properties||{};await dispatchMonitorNotification(m,p.event||'Severe weather alert',p.headline||'Official NWS alert is active','/?tab=alerts',true);sent.push(`severe:${alert.id}`)}state.alertIds=delta.activeIds;delete state.alertId;}
   if(m.preferences?.planChanges!==false){for(const plan of(m.plans||[])){const risk:any=riskForPlan(plan,w,null),key=`plan:${plan.id}`,next={level:risk.level,rain:Math.round(risk.metrics?.rain||0),wind:Math.round(risk.metrics?.wind||0),high:Math.round(risk.metrics?.high||0),low:Math.round(risk.metrics?.low||0)};if(meaningfulPlanChange(state[key],next)&&['watch','bad'].includes(risk.level)){await dispatchMonitorNotification(m,`${plan.name}: ${risk.label}`,risk.reasons.join(' · '),'/?tab=plans');sent.push(key)}state[key]=next;}}
   if(m.preferences?.rainSoon){const rt:any=rainTiming(w),sig=rt?.kind+':'+(rt?.time||'');if(['starting','stopping'].includes(rt?.kind)&&state.rainTiming!==sig){await dispatchMonitorNotification(m,rt.kind==='starting'?'Rain may start soon':'Rain may ease soon',rt.label,'/');sent.push(`rain-${rt.kind}`)}state.rainTiming=sig;}
   if(m.preferences?.aqi&&typeof aq?.current?.us_aqi==='number'){const aqi=Math.round(aq.current.us_aqi),band=aqi>=151?'unhealthy':aqi>=101?'sensitive':'ok';if(band!=='ok'&&state.aqiBand!==band){await dispatchMonitorNotification(m,'Air quality alert',`US AQI is ${aqi} near ${loc.name}. Consider adjusting prolonged outdoor plans.`,'/?tab=health');sent.push('aqi')}state.aqiBand=band;}
   if(m.preferences?.lightning&&lt){const miles=lightningDistance(lt);if(typeof miles==='number'){const band=miles<=5?5:miles<=10?10:miles<=15?15:99;if(band<99&&band!==state.lightningBand){await dispatchMonitorNotification(m,'Lightning nearby',`Verified lightning detected within ${Math.round(miles)} miles of ${loc.name}.`,'/?tab=storm',band<=5);sent.push(`lightning-${band}`)}state.lightningBand=band;}}
   await setMonitor(id,{...m,state,lastCheckedAt:new Date().toISOString()});summary.push({id,sent});
 }catch(e:any){summary.push({id,error:e?.message||'failed'});}}
 return NextResponse.json({ok:true,checked:monitors.length,summary});
}
