'use client';
import { useEffect, useRef, useState } from 'react';
type Frame={time:number;path:string};type RadarMeta={host:string;radar?:{past?:Frame[];nowcast?:Frame[]}};
export default function RadarMap({lat,lon,lightning}:{lat:number;lon:number;lightning?:any}){
 const containerRef=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),radarLayerRef=useRef<any>(null),fireLayerRef=useRef<any>(null),lightningLayerRef=useRef<any>(null);
 const [meta,setMeta]=useState<RadarMeta|null>(null),[frameIndex,setFrameIndex]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[showFires,setShowFires]=useState(false),[showLightning,setShowLightning]=useState(false),[fires,setFires]=useState<any>({configured:false,fires:[]});
 const frames=meta?.radar?.past??[],frame=frames[frameIndex];
 useEffect(()=>{let alive=true;fetch('/api/radar').then(r=>r.json()).then((d:RadarMeta)=>{if(!alive)return;setMeta(d);const n=d.radar?.past?.length??0;setFrameIndex(Math.max(0,n-1));}).catch(()=>setError('Radar data is temporarily unavailable.'));return()=>{alive=false}},[]);
 useEffect(()=>{fetch(`/api/fires?lat=${lat}&lon=${lon}`).then(r=>r.json()).then(setFires).catch(()=>setFires({configured:false,fires:[]}));},[lat,lon]);
 useEffect(()=>{if(!containerRef.current||mapRef.current)return;let destroyed=false;import('leaflet').then(mod=>{if(destroyed||!containerRef.current)return;const L=mod.default;const map=L.map(containerRef.current,{zoomControl:false,attributionControl:true}).setView([lat,lon],7);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);L.circleMarker([lat,lon],{radius:6,weight:2,fillOpacity:1}).addTo(map);mapRef.current=map;}).catch(()=>setError('Map failed to initialize.'));return()=>{destroyed=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[]);
 useEffect(()=>{if(mapRef.current)mapRef.current.setView([lat,lon],mapRef.current.getZoom());},[lat,lon]);
 useEffect(()=>{if(!mapRef.current||!meta?.host||!frame)return;let cancelled=false;import('leaflet').then(mod=>{if(cancelled||!mapRef.current)return;const L=mod.default;if(radarLayerRef.current)mapRef.current.removeLayer(radarLayerRef.current);radarLayerRef.current=L.tileLayer(`${meta.host}${frame.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.72,maxNativeZoom:7,maxZoom:18,attribution:'Radar: RainViewer'}).addTo(mapRef.current)});return()=>{cancelled=true}},[meta,frame]);
 useEffect(()=>{if(!playing||frames.length<2)return;const id=window.setInterval(()=>setFrameIndex(i=>(i+1)%frames.length),650);return()=>window.clearInterval(id)},[playing,frames.length]);
 useEffect(()=>{if(!mapRef.current)return;import('leaflet').then(mod=>{const L=mod.default;if(fireLayerRef.current){mapRef.current.removeLayer(fireLayerRef.current);fireLayerRef.current=null}if(showFires&&fires.fires?.length){const group=L.layerGroup();fires.fires.forEach((f:any)=>L.circleMarker([f.latitude,f.longitude],{radius:4,weight:1,fillOpacity:.75}).bindPopup(`<b>Satellite fire hotspot</b><br>${f.acq_date||''} ${f.acq_time||''}<br>FRP ${Number.isFinite(f.frp)?f.frp:'—'}`).addTo(group));group.addTo(mapRef.current);fireLayerRef.current=group;}});},[showFires,fires]);
 useEffect(()=>{if(!mapRef.current)return;import('leaflet').then(mod=>{const L=mod.default;if(lightningLayerRef.current){mapRef.current.removeLayer(lightningLayerRef.current);lightningLayerRef.current=null}if(showLightning&&lightning?.strikes?.length){const group=L.layerGroup();lightning.strikes.filter((s:any)=>Number.isFinite(Number(s.latitude??s.lat))&&Number.isFinite(Number(s.longitude??s.lon))).forEach((s:any)=>L.circleMarker([Number(s.latitude??s.lat),Number(s.longitude??s.lon)],{radius:5,weight:2,fillOpacity:.8}).bindPopup(`<b>Verified lightning strike</b><br>${s.time?new Date(s.time).toLocaleString():''}`).addTo(group));group.addTo(mapRef.current);lightningLayerRef.current=group;}});},[showLightning,lightning]);
 return <div className="radar-wrap"><div className="radar-map" ref={containerRef}/><div className="radar-floating radar-layer-panel"><b>Layers</b><label><input type="checkbox" checked={showLightning} disabled={!lightning?.configured} onChange={e=>setShowLightning(e.target.checked)}/> Lightning {lightning?.configured?'':'(provider needed)'}</label><label><input type="checkbox" checked={showFires} disabled={!fires.configured} onChange={e=>setShowFires(e.target.checked)}/> Fire hotspots {fires.configured?'':'(FIRMS key needed)'}</label></div><div className="radar-floating radar-legend"><b>Reflectivity</b><div className="legend-gradient"/><div className="legend-labels"><span>Light</span><span>Heavy</span></div></div><div className="radar-controls"><button className="play-button" onClick={()=>setPlaying(p=>!p)}>{playing?'Ⅱ':'▶'}</button><div className="timeline-block"><div className="timeline-meta"><span>{frame?new Date(frame.time*1000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Loading radar…'}</span><span>{frames.length?`${frameIndex+1} / ${frames.length}`:''}</span></div><input aria-label="Radar time" type="range" min={0} max={Math.max(0,frames.length-1)} value={frameIndex} onChange={e=>{setPlaying(false);setFrameIndex(Number(e.target.value))}}/></div></div>{error&&<div className="radar-error">{error}</div>}</div>;
}
